name: Deploy React Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          # If the line below had a '#' at the beginning, remove it and change 'true' to 'false'.
          # For example, if you saw: # CI: true
          # Change it to:
          CI: false # This prevents ESLint from treating warnings as errors during the build
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'whichfood-frontend'
          slot-name: 'Production'
          package: ./frontend/build
