name: Deploy React Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # CRUCIAL for OpenID Connect (OIDC) authentication
      contents: read # Required for actions/checkout

    environment: # <--- ADD THIS LINE (at the job level)
      name: 'Production' # <--- ADD THIS LINE (Matching your backend setup)
      # You can add url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} here too if you want.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          CI: false # Keep this if you want to ignore ESLint warnings during build
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp # <--- Add an ID so you can reference its output for environment URL
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'whichfood-frontend'
          slot-name: 'Production'
          package: ./frontend/build
